CREATE TYPE status_exemplar_enum AS ENUM (
    'disponivel',
    'processando',
    'emprestado',
    'danificado',
    'indisponivel'
);

CREATE TABLE exemplares (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    livro_id integer NOT NULL,
    status status_exemplar_enum NOT NULL DEFAULT 'disponivel',

    codigo text GENERATED BY DEFAULT AS (
    'EX-' || LPAD(id::text, 6, '0')
    ) STORED NOT NULL UNIQUE,

    CONSTRAINT exemplares_livros_id_fk
        FOREIGN KEY (livro_id)
        REFERENCES livros (id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);